### PR TITLE
Indy500 archive support

### PR DESCRIPTION
**Pull request by colinbourassa**

### CODE REVIEW

**Comment by colinbourassa** [comment]
The CI check failures are due to a version mismatch of gamecomp, which must be >= 2.7.0 for Indy500 archive support. This PR modifies package.json with the updated version requirement, but it looks like something else is required. What have I missed?

**Comment by Malvineous** [comment]
If you run `npm install @camoto/gamecomp@latest` it should automatically update the version in `package.json` but more importantly it will also update it in `package-lock.json`.  By default `package.json` only gives you approximate versions and newer ones will be installed if available according to certain semver rules, however when the CI tests run they use `npm ci` instead of `npm install` which only uses the specific versions listed in `package-lock.json` - no automatic version upgrades.  (This is designed for continuous deployment systems so that the version you test is guaranteed to be the same as the version you deploy, which wouldn't happen if `npm install` were used as a package may get upgraded between the test and deploy.)

If you want to try this and amend the PR to include the changes to `package-lock.json` then the tests should pass successfully.  (Feel free to just amend the 2.7.0 commit and force-push the branch used for the PR).

**Comment by colinbourassa** [comment]
Thanks for the info! I had to upgrade to a more recent nodejs/npm version, but this seems to be working now.

**Comment by Malvineous** [comment]
Perfect, many thanks!

**Pull request merged**
